# Generated by Django 3.1.4 on 2021-01-04 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20210104_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='subname',
            field=models.CharField(blank=True, max_length=128, verbose_name='Второе имя'),
        ),
    ]
