# Generated by Django 3.1.4 on 2021-01-04 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_remove_product_subname'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainSlider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=128, verbose_name='Заголовок')),
                ('text', models.CharField(max_length=512, verbose_name='Текст')),
                ('short_text', models.CharField(blank=True, max_length=256, verbose_name='Короткий текст')),
                ('image', models.ImageField(blank=True, upload_to='product_images')),
                ('back_image', models.ImageField(upload_to='product_images')),
            ],
        ),
    ]
