# Generated by Django 3.1.4 on 2021-01-05 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_mainslider'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='OpenCritic',
            field=models.CharField(choices=[('Bad', 'Bad'), ('Alright', 'Alright'), ('Good', 'Good'), ('Perfect', 'Perfect')], default='Bad', max_length=16, verbose_name='Оценка OpenCritic'),
        ),
        migrations.AddField(
            model_name='product',
            name='metacritic',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='pcGamer',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
