# Generated by Django 3.1.4 on 2021-01-06 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_auto_20210106_2003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_big',
        ),
    ]
