# Generated by Django 3.1.4 on 2021-02-04 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_product_is_big'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name': 'Галлерея', 'verbose_name_plural': 'Галлереи'},
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(blank=True, max_length=2048, upload_to='product_images'),
        ),
        migrations.AlterField(
            model_name='mainslider',
            name='header',
            field=models.CharField(max_length=512, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=512, verbose_name='имя'),
        ),
        migrations.AlterField(
            model_name='product',
            name='short_desc',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
